<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_90002</name>
   <tag></tag>
   <elementGuidId>c5f0d7ef-c6a9-4247-bb86-fc8a1770b0c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-view']/div/ui-view/section/md-content/md-content/ui-view/agentfarm/section/div[3]/area-manager/div/div/div/form/div/div/react-lr-autocomplete/div/div/div/nav/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.jss619</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root jss619</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>90002</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-view&quot;)/div[1]/ui-view[@class=&quot;ng-scope&quot;]/section[@class=&quot;loggedin-wrapper ng-scope layout-row flex&quot;]/md-content[@class=&quot;header-content-wrap _md&quot;]/md-content[@class=&quot;content-wrap _md&quot;]/ui-view[@class=&quot;ng-scope&quot;]/agentfarm[@class=&quot;ng-scope&quot;]/section[@class=&quot;agentfarm ng-scope layout-column&quot;]/div[@class=&quot;area-manager-wrapper ng-scope&quot;]/area-manager[@class=&quot;ng-scope ng-isolate-scope&quot;]/div[@class=&quot;area-manager hide-xs&quot;]/div[@class=&quot;pills layout-wrap ng-scope layout-align-start-start layout-row&quot;]/div[@class=&quot;pill-wrap ng-scope&quot;]/form[@class=&quot;form ng-pristine ng-valid&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;lr-input-btn-group&quot;]/react-lr-autocomplete[1]/div[@class=&quot;MuiBox-root jss588&quot;]/div[@class=&quot;MuiBox-root jss602&quot;]/div[1]/nav[@class=&quot;MuiList-root sc-RefOD cfVAbi MuiList-padding&quot;]/div[@class=&quot;MuiBox-root jss618&quot;]/div[@class=&quot;MuiBox-root jss619&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-view']/div/ui-view/section/md-content/md-content/ui-view/agentfarm/section/div[3]/area-manager/div/div/div/form/div/div/react-lr-autocomplete/div/div/div/nav/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Median DOM'])[1]/following::div[11]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Median Price'])[1]/following::div[14]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/preceding::div[9]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='90002']/parent::*</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/div</value>
   </webElementXpaths>
</WebElementEntity>
