<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_How to use the photo selector_w-css-reset</name>
   <tag></tag>
   <elementGuidId>bb6e8a90-b999-45da-8d55-4240eb65d272</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='w-vulcan-v2-100']/div/div[3]/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-css-reset</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://embed-ssl.wistia.com/deliveries/74096025b11ea5ff8eebfdcdb112cef2.webp?image_crop_resized=640x359 320w, https://embed-ssl.wistia.com/deliveries/74096025b11ea5ff8eebfdcdb112cef2.webp?image_crop_resized=640x359 640w, https://embed-ssl.wistia.com/deliveries/74096025b11ea5ff8eebfdcdb112cef2.webp?image_crop_resized=930x521 960w, https://embed-ssl.wistia.com/deliveries/74096025b11ea5ff8eebfdcdb112cef2.webp?image_crop_resized=930x521 1280w, https://embed-ssl.wistia.com/deliveries/74096025b11ea5ff8eebfdcdb112cef2.webp?image_crop_resized=930x521 1920w, https://embed-ssl.wistia.com/deliveries/74096025b11ea5ff8eebfdcdb112cef2.webp?image_crop_resized=930x521 3840w</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://embed-ssl.wistia.com/deliveries/74096025b11ea5ff8eebfdcdb112cef2.webp?image_crop_resized=640x359</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Video Thumbnail</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w-vulcan-v2-100&quot;)/div[@class=&quot;w-vulcan--background w-css-reset&quot;]/div[@class=&quot;w-css-reset&quot;]/div[1]/div[@class=&quot;w-css-reset&quot;]/img[@class=&quot;w-css-reset&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='w-vulcan-v2-100']/div/div[3]/div/div[2]/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Video Thumbnail'])[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div[2]/div[2]/div[2]/div/div/div[3]/div/div[2]/img</value>
   </webElementXpaths>
</WebElementEntity>
