<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_How to edit a marketing kit_w-css-reset</name>
   <tag></tag>
   <elementGuidId>8e8289e2-9df6-4e9d-9e25-8979a58e979a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='w-vulcan-v2-79']/div/div[3]/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-css-reset</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://embed-ssl.wistia.com/deliveries/0153f6df887de8071ad3f84ca68c9375.webp?image_crop_resized=640x323 320w, https://embed-ssl.wistia.com/deliveries/0153f6df887de8071ad3f84ca68c9375.webp?image_crop_resized=640x323 640w, https://embed-ssl.wistia.com/deliveries/0153f6df887de8071ad3f84ca68c9375.webp?image_crop_resized=936x473 960w, https://embed-ssl.wistia.com/deliveries/0153f6df887de8071ad3f84ca68c9375.webp?image_crop_resized=936x473 1280w, https://embed-ssl.wistia.com/deliveries/0153f6df887de8071ad3f84ca68c9375.webp?image_crop_resized=936x473 1920w, https://embed-ssl.wistia.com/deliveries/0153f6df887de8071ad3f84ca68c9375.webp?image_crop_resized=936x473 3840w</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://embed-ssl.wistia.com/deliveries/0153f6df887de8071ad3f84ca68c9375.webp?image_crop_resized=640x323</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Video Thumbnail</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w-vulcan-v2-79&quot;)/div[@class=&quot;w-vulcan--background w-css-reset&quot;]/div[@class=&quot;w-css-reset&quot;]/div[1]/div[@class=&quot;w-css-reset&quot;]/img[@class=&quot;w-css-reset&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='w-vulcan-v2-79']/div/div[3]/div/div[2]/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Video Thumbnail'])[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/div[2]/div[2]/div/div/div[3]/div/div[2]/img</value>
   </webElementXpaths>
</WebElementEntity>
