<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click for sound_w-css-reset</name>
   <tag></tag>
   <elementGuidId>85bf30a7-e7cb-41ad-8c0f-194557affb61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='w-vulcan-v2-28']/div/div[3]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.w-css-reset</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-css-reset</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://embed-ssl.wistia.com/deliveries/b10ffe5ac6b41406824a9fe8fa718cb1.jpg?image_crop_resized=640x360 320w, https://embed-ssl.wistia.com/deliveries/b10ffe5ac6b41406824a9fe8fa718cb1.jpg?image_crop_resized=640x360 640w, https://embed-ssl.wistia.com/deliveries/b10ffe5ac6b41406824a9fe8fa718cb1.jpg?image_crop_resized=960x540 960w, https://embed-ssl.wistia.com/deliveries/b10ffe5ac6b41406824a9fe8fa718cb1.jpg?image_crop_resized=1280x720 1280w, https://embed-ssl.wistia.com/deliveries/b10ffe5ac6b41406824a9fe8fa718cb1.jpg?image_crop_resized=1920x1080 1920w, https://embed-ssl.wistia.com/deliveries/b10ffe5ac6b41406824a9fe8fa718cb1.jpg?image_crop_resized=1920x1080 3840w</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://embed-ssl.wistia.com/deliveries/b10ffe5ac6b41406824a9fe8fa718cb1.jpg?image_crop_resized=1920x1080</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Video Thumbnail</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w-vulcan-v2-28&quot;)/div[@class=&quot;w-vulcan--background w-css-reset&quot;]/div[@class=&quot;w-css-reset&quot;]/div[1]/div[@class=&quot;w-css-reset&quot;]/img[@class=&quot;w-css-reset&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='w-vulcan-v2-28']/div/div[3]/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Video Thumbnail']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
   </webElementXpaths>
</WebElementEntity>
